---
- hosts: localhost

  tasks:
    - terraform:
        project_path: './'
        state: present
      register: terraform_data

    - name: Add web vm to inventory
      add_host:
        name: '{{ terraform_data.outputs.web_ip.value }}'
        groups: web

    - name: wait for ssh to be available on vm
      wait_for:
        port: 22
        host: '{{ terraform_data.outputs.web_ip.value }}'
        search_regex: OpenSSH
      connection: local

- hosts: web

  tasks:
    - name: Clone project
      git:
        repo: https://github.com/kevindurb/node-ansible-terraform-packer-test.git
        dest: /home/kevindurb/server

    - name: install deps
      npm:
        path: /home/kevindurb/server/server

    - name: start node server
      shell:
        chdir: /home/kevindurb/server/server
        cmd: nohup node ./index.js </dev/null >/dev/null 2>&1 &
