---
- hosts: default
  become: true

  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install node
      apt:
        name: 'nodejs'
        state: present
        update_cache: yes

    - name: install npm
      apt:
        name: 'npm'
        state: present
        update_cache: yes

    - name: create user
      user:
        name: kevindurb
        shell: "/bin/bash"

    - name: make sure kevindurb owns everything in home
      file:
        path: /home/kevindurb
        owner: kevindurb
        recurse: yes

    - name: Set authorized keys taken from github
      authorized_key:
        user: kevindurb
        state: present
        key: https://github.com/kevindurb.keys
